version: '3.7'

services:
  server:
    entrypoint: [ "sh", "-c", "java -cp app:app/lib/* br.com.desafio.managementapi" ]
    network_mode: 'host'
    environment:
      - SPRING_PROFILES_ACTIVE=dev


    depends_on:
      - db

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=managementdb