spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  flyway:
    baseline: true
    locations: src/main/resources/db/migration


swagger:
  contact:
    name: 'Filipe Chiconello'
    email: "filipe360@gmail.com"
  app:
    name: Management API
    version: 0.1.0
    description: API responsible for registering and querying projects and employees.
  base:
    package: br.com.desafio.managementapi.controllers

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path:
      path-mapping:
        health: /healthcheck